function U(v){return String(v??'').trim().toUpperCase()}
function injectUniversalStyle(){if(document.getElementById('universalFixStyle'))return;const st=document.createElement('style');st.id='universalFixStyle';st.textContent=`.brand h1{font-size:34px!important;letter-spacing:.5px}.brand div{font-size:14px}.big-workspace{grid-template-columns:repeat(2,1fr)!important}.big-workspace .btn{min-height:105px!important;font-size:19px!important;padding:20px!important;display:flex;align-items:center;justify-content:center;gap:8px}.big-workspace .btn:first-letter{font-size:30px}.quick button{font-size:15px!important;padding:10px 13px!important;min-height:42px}.formulation{font-style:italic;font-weight:400}.print-content{text-transform:uppercase}`;document.head.appendChild(st)}
function ensureDoseButtons(){const q=document.querySelector('#medRows')?.parentElement?.nextElementSibling;if(!q)return;[['0-0-5ml',0],['30 days',1]].forEach(([txt,type])=>{if([...q.querySelectorAll('button')].some(b=>b.textContent.trim()===txt))return;const b=document.createElement('button');b.type='button';b.textContent=txt;b.onclick=()=>type===0?setLastFrequency('0-0-5ml'):setLastDuration('30 days');q.appendChild(b)})}
function fixConsultationUI(){injectUniversalStyle();const home=document.querySelector('#homeView .grid');if(home)home.classList.add('big-workspace');document.querySelectorAll('#homeView .grid .btn,.nav .btn,.actions .btn,.quick button,#templateQuick button').forEach(b=>b.setAttribute('tabindex','-1'));const th=document.querySelector('#consultView .table thead tr');if(th&&th.children[0]&&th.children[0].textContent.trim()==='#')th.removeChild(th.children[0]);document.querySelectorAll('#medRows tr').forEach(r=>{if(r.children[0]&&/^\d+$/.test(r.children[0].textContent.trim()))r.removeChild(r.children[0])});ensureDoseButtons()}
function addMedicineRow(m={}){let tr=document.createElement('tr');tr.innerHTML=`<td><div class="rel"><input class="medname" autocomplete="off" placeholder="TYPE MEDICINE" value="${esc(m.medicine_name||m.name||'')}"></div></td><td><input class="medstrength" value="${esc(m.strength||'')}"></td><td><input class="medfreq" value="${esc(m.frequency||m.default_frequency||'')}"></td><td><input class="meddur" value="${esc(m.duration||m.default_duration||'')}"></td><td><input class="medinst" value="${esc(m.instruction||m.default_instruction||'')}"></td><td><button class="btn danger" type="button" tabindex="-1">×</button></td>`;$('medRows').appendChild(tr);lastMedRow=tr;let inp=tr.querySelector('.medname');inp.addEventListener('input',()=>showMedicineSuggestions(inp));inp.addEventListener('keydown',e=>{if(e.key==='Enter'){findMedicines(inp.value).then(a=>{if(a[0]){fillMedicine(inp,a[0]);focusAfter(inp)}});e.preventDefault()}});tr.querySelector('button').onclick=()=>tr.remove();tr.querySelectorAll('input').forEach(x=>x.addEventListener('focus',()=>lastMedRow=tr));return tr}
function insertText(id,text){const e=$(id);if(!e)return;e.focus();const start=e.selectionStart??e.value.length,end=e.selectionEnd??e.value.length,before=e.value.slice(0,start),after=e.value.slice(end),prefix=before.trim()?(/[\s,]$/.test(before)?'':', '):'';e.value=before+prefix+text+after;e.selectionStart=e.selectionEnd=start+prefix.length+text.length;e.dispatchEvent(new Event('input',{bubbles:true}))}
function renderQuickButtons(){const x=quickData(),map={complaints:'complaintQuick',known:'knownQuick',habits:'habitQuick',history:'historyQuick',examination:'examinationQuick',diagnosis:'diagnosisQuick',investigations:'investigationQuick',advice:'adviceQuick'},targets={complaints:'complaints',known:'knownCases',habits:'habits',history:'historyOf',examination:'examination',diagnosis:'diagnosis',investigations:'investigations',advice:'advice'};Object.entries(map).forEach(([cat,id])=>{const box=$(id);if(!box)return;box.innerHTML='';(x[cat]||[]).forEach(q=>{const b=document.createElement('button');b.type='button';b.tabIndex=-1;b.textContent=q.label;b.dataset.target=targets[cat];b.dataset.text=q.text;b.onclick=e=>{e.preventDefault();insertText(b.dataset.target,b.dataset.text)};box.appendChild(b)})})}
function renderTemplateQuick(){$('templateQuick').innerHTML=templateData().map(t=>`<button type="button" tabindex="-1" onclick="applyTemplate('${t.id}')">📋 ${esc(t.name)}</button>`).join('')||'<span class="muted">NO TREATMENT TEMPLATES YET.</span>'}
function setupConsultTabOrder(){const root=$('consultView');if(!root||root.dataset.tabfix==='1')return;root.dataset.tabfix='1';root.addEventListener('keydown',e=>{if(e.key!=='Tab'||e.shiftKey)return;const controls=[...root.querySelectorAll('input,select,textarea')].filter(el=>!el.disabled&&!el.readOnly&&el.offsetParent!==null&&el.tabIndex!==-1);const i=controls.indexOf(e.target);if(i<0)return;e.preventDefault();const next=controls[i+1];if(next)next.focus()})}
async function preparePrint(v,p){let s=await session();let meds=(await S.from('prescriptions').select('*').eq('visit_id',v.id).eq('doctor_id',s.user.id).order('sort_order')).data||[];let parts=[];const add=(label,val)=>{if(val!==null&&val!==undefined&&String(val).trim()&&String(val).trim()!=='—')parts.push(`<div class="pblock"><b>${U(label)}:</b> ${U(val)}</div>`)};add('Patient',p.name);add('Age / Sex',[p.age,p.gender].filter(Boolean).join(' / '));add('Date',v.visit_date);let vit=[['BP',v.bp],['BSL',v.blood_sugar],['SpO2',v.spo2],['Temp',v.temperature],['Pulse',v.pulse],['Weight',v.weight]].filter(x=>x[1]);if(vit.length)add('Vitals',vit.map(x=>U(x[0])+': '+U(x[1])).join('   '));add('Complaints',v.complaints);let ex=getVisitExtras(v.id);add('Known Case Of',ex.knownCases);add('Habbits',ex.habits);add('History Of',ex.historyOf);add('Examination',ex.examination);add('Diagnosis',v.diagnosis);add('Investigations',v.investigations);if(meds.length)parts.push(`<div class="pblock"><b>PRESCRIPTION:</b></div><table class="rx"><tr><th>MEDICINE</th><th>FREQUENCY / DOSE</th><th>DURATION</th><th>INSTRUCTION</th></tr>${meds.map(m=>`<tr><td><b>${U(m.medicine_name)}</b>${m.strength&&String(m.strength).trim()?`<div class="formulation">${U(m.strength)}</div>`:''}</td><td>${U(m.frequency)}</td><td>${U(m.duration)}</td><td>${U(m.instruction)}</td></tr>`).join('')}</table>`);add('Advice / Follow-Up',v.advice);$('printContent').innerHTML=parts.join('')}
function openPrintWindow(size){const w=window.open('','_blank','width=900,height=1000');if(!w)return alert('PLEASE ALLOW POP-UPS FOR PRINTING.');const a4=size==='a4',width=a4?'144mm':'101mm',top=a4?'27mm':'25mm',left='5mm',font=a4?'11px':'10px';const html=`<!doctype html><html><head><title>PRESCRIPTION</title><style>@page{size:${a4?'A4':'A5'} portrait;margin:0}html,body{margin:0;padding:0;background:#fff}body{font-family:Arial,sans-serif;color:#111;text-transform:uppercase}.sheet{position:absolute;left:${left};top:${top};width:${width};font-size:${font};line-height:1.3}.pblock{margin:2.5px 0}.rx{width:100%;border-collapse:collapse;margin:5px 0;table-layout:fixed}.rx th,.rx td{border:1px solid #777;padding:3px;text-align:left;vertical-align:top;word-wrap:break-word}.rx th:nth-child(1){width:38%}.rx th:nth-child(2){width:22%}.rx th:nth-child(3){width:16%}.rx th:nth-child(4){width:24%}.formulation{font-style:italic;font-weight:400;text-transform:uppercase;margin-top:1px}.print-sign{margin-top:12px;text-align:right;font-weight:700}</style></head><body><div class="sheet">${$('printContent').innerHTML}</div></body></html>`;w.document.write(html);w.document.close();setTimeout(()=>w.print(),350);w.onafterprint=()=>w.close()}
async function newConsultFromVisit(id){let s=await session(),v=(await S.from('visits').select('*').eq('id',id).eq('doctor_id',s.user.id).single()).data;if(!v)return;closeModal('patientModal');newConsultFromHistory();currentVisit=v;$('complaints').value=v.complaints||'';let ex=getVisitExtras(v.id);$('knownCases').value=ex.knownCases||'';$('habits').value=ex.habits||'';$('historyOf').value=ex.historyOf||'';$('examination').value=ex.examination||'';$('diagnosis').value=v.diagnosis||'';$('investigations').value=v.investigations||'';$('advice').value=v.advice||'';$('bp').value=v.bp||'';$('pulse').value=v.pulse||'';$('spo2').value=v.spo2||'';$('temperature').value=v.temperature||'';$('weight').value=v.weight||'';$('sugar').value=v.blood_sugar||'';let meds=(await S.from('prescriptions').select('*').eq('visit_id',id).eq('doctor_id',s.user.id).order('sort_order')).data||[];$('medRows').innerHTML='';meds.forEach(addMedicineRow);if(!meds.length)addMedicineRow();$('consultMode').textContent='New consultation for '+currentPatient.name;route('consult');fixConsultationUI();setupConsultTabOrder()}
async function reviewVisit(id,size){let s=await session(),v=(await S.from('visits').select('*').eq('id',id).eq('doctor_id',s.user.id).single()).data;if(!v)return;await preparePrint(v,currentPatient);openPrintWindow(size)}
async function deleteVisit(id){if(!confirm('DELETE THIS VISIT AND ITS PRESCRIPTION?'))return;let s=await session();await S.from('prescriptions').delete().eq('visit_id',id).eq('doctor_id',s.user.id);let r=await S.from('visits').delete().eq('id',id).eq('doctor_id',s.user.id);removeVisitExtras(id);if(r.error)alert(r.error.message);else openHistory(currentPatient.id)}
async function deletePatient(){if(!currentPatient)return;if(!confirm('DELETE THIS PATIENT AND ALL HISTORY?'))return;if(!confirm('FINAL: PERMANENTLY DELETE '+currentPatient.name+'?'))return;let s=await session(),vs=(await S.from('visits').select('id').eq('patient_id',currentPatient.id).eq('doctor_id',s.user.id)).data||[];for(let v of vs){await S.from('prescriptions').delete().eq('visit_id',v.id).eq('doctor_id',s.user.id);removeVisitExtras(v.id)}await S.from('visits').delete().eq('patient_id',currentPatient.id).eq('doctor_id',s.user.id);let r=await S.from('patients').delete().eq('id',currentPatient.id).eq('doctor_id',s.user.id);if(r.error)alert(r.error.message);else{closeModal('patientModal');currentPatient=null;loadPatients()}}
function closeModal(id){$(id).classList.remove('on')}
async function loadMedicines(){let s=await session();if(!s)return;let q=$('medicineSearch').value.toLowerCase().trim(),r=await S.from('medicines').select('*').eq('doctor_id',s.user.id).order('name').limit(500),words=q.split(/\s+/).filter(Boolean),a=(r.data||[]).filter(m=>{let t=[m.name,m.strength,m.default_frequency,m.default_duration,m.default_instruction].join(' ').toLowerCase();return words.every(w=>t.includes(w))});$('medicineList').innerHTML=a.map(m=>`<div class="listrow"><div><b>${esc(m.name)}</b><div class="muted">${esc(m.strength||'')} • ${esc(m.default_frequency||'')} • ${esc(m.default_duration||'')}</div></div><div class="actions"><button class="btn" onclick="editMedicine('${m.id}')">EDIT</button><button class="btn primary" onclick="useMedicine('${m.id}')">USE</button><button class="btn danger" onclick="deleteMedicine('${m.id}')">DELETE</button></div></div>`).join('')||'<p class="muted">NO MEDICINES FOUND.</p>'}
function openMedicineEditor(m=null){editingMedId=m?.id||null;$('medEditorTitle').textContent=m?'EDIT MEDICINE':'ADD MEDICINE';$('medName').value=m?.name||'';$('medStrength').value=m?.strength||'';$('medFrequency').value=m?.default_frequency||'';$('medDuration').value=m?.default_duration||'';$('medInstruction').value=m?.default_instruction||'';$('medicineEditor').classList.add('on')}
async function editMedicine(id){let s=await session(),m=(await S.from('medicines').select('*').eq('id',id).eq('doctor_id',s.user.id).single()).data;if(m)openMedicineEditor(m)}
async function saveMedicine(){let s=await session(),name=$('medName').value.trim();if(!name)return alert('ENTER MEDICINE NAME.');let obj={name,strength:$('medStrength').value,default_frequency:$('medFrequency').value,default_duration:$('medDuration').value,default_instruction:$('medInstruction').value};let r=editingMedId?await S.from('medicines').update(obj).eq('id',editingMedId).eq('doctor_id',s.user.id):await S.from('medicines').insert({...obj,doctor_id:s.user.id});if(r.error)return alert(r.error.message);closeModal('medicineEditor');loadMedicines()}
async function deleteMedicine(id){if(!confirm('DELETE THIS MEDICINE FROM THE SHARED LIBRARY?'))return;let s=await session(),r=await S.from('medicines').delete().eq('id',id).eq('doctor_id',s.user.id);if(r.error)alert(r.error.message);else loadMedicines()}
async function useMedicine(id){let s=await session(),m=(await S.from('medicines').select('*').eq('id',id).eq('doctor_id',s.user.id).single()).data;if(!m)return;route('consult');addMedicineRow(m);fixConsultationUI()}
function showQuickCategory(cat){quickCategory=cat;let x=quickData()[cat]||[];$('quickList').innerHTML=x.map(q=>`<div class="listrow"><div><b>${esc(q.label)}</b><div class="muted">${esc(q.text)}</div></div><div class="actions"><button class="btn" onclick="editQuick('${q.id}')">EDIT</button><button class="btn danger" onclick="deleteQuick('${q.id}')">DELETE</button></div></div>`).join('')||'<p class="muted">NO SHORTCUTS.</p>'}
function openQuickEditor(q=null){editingQuickId=q?.id||null;$('quickCat').value=q?.cat||quickCategory;$('quickLabel').value=q?.label||'';$('quickText').value=q?.text||'';$('quickEditor').classList.add('on')}
function editQuick(id){let x=quickData();for(let cat of Object.keys(x)){let q=x[cat].find(a=>a.id===id);if(q){openQuickEditor({...q,cat});return}}}
function saveQuick(){let x=quickData(),cat=$('quickCat').value,label=$('quickLabel').value.trim(),text=$('quickText').value.trim();if(!label||!text)return alert('ENTER BUTTON NAME AND TEXT.');Object.keys(x).forEach(k=>x[k]=(x[k]||[]).filter(q=>q.id!==editingQuickId));x[cat]=x[cat]||[];x[cat].push({id:editingQuickId||'q_'+Date.now(),label,text});saveQuickData(x);closeModal('quickEditor');showQuickCategory(cat);renderQuickButtons()}
function deleteQuick(id){if(!confirm('DELETE THIS SHORTCUT?'))return;let x=quickData();Object.keys(x).forEach(k=>x[k]=(x[k]||[]).filter(q=>q.id!==id));saveQuickData(x);showQuickCategory(quickCategory);renderQuickButtons()}
function openTemplateEditor(t=null){editingTemplateId=t?.id||null;$('templateEditorTitle').textContent=t?'EDIT TREATMENT TEMPLATE':'ADD TREATMENT TEMPLATE';['tplName','tplDiagnosis','tplComplaints','tplKnown','tplHabits','tplHistory','tplExam','tplInvestigations','tplAdvice'].forEach(id=>$(id).value='');$('tplMedRows').innerHTML='';if(t){$('tplName').value=t.name||'';$('tplDiagnosis').value=t.diagnosis||'';$('tplComplaints').value=t.complaints||'';$('tplKnown').value=t.known||'';$('tplHabits').value=t.habits||'';$('tplHistory').value=t.history||'';$('tplExam').value=t.exam||'';$('tplInvestigations').value=t.investigations||'';$('tplAdvice').value=t.advice||'';(t.medicines||[]).forEach(addTemplateMedRow)}$('templateEditor').classList.add('on')}
function addTemplateMedRow(m={}){let tr=document.createElement('tr');tr.innerHTML=`<td><input class="tmn" value="${esc(m.medicine_name||'')}"></td><td><input class="tms" value="${esc(m.strength||'')}"></td><td><input class="tmf" value="${esc(m.frequency||'')}"></td><td><input class="tmd" value="${esc(m.duration||'')}"></td><td><input class="tmi" value="${esc(m.instruction||'')}"></td><td><button class="btn danger" type="button" tabindex="-1">×</button></td>`;$('tplMedRows').appendChild(tr);tr.querySelector('button').onclick=()=>tr.remove();return tr}
function saveTemplate(){let x=templateData(),t={id:editingTemplateId||'t_'+Date.now(),name:$('tplName').value.trim(),diagnosis:$('tplDiagnosis').value,complaints:$('tplComplaints').value,known:$('tplKnown').value,habits:$('tplHabits').value,history:$('tplHistory').value,exam:$('tplExam').value,investigations:$('tplInvestigations').value,advice:$('tplAdvice').value,medicines:[...$('tplMedRows').rows].map(r=>({medicine_name:r.querySelector('.tmn').value,strength:r.querySelector('.tms').value,frequency:r.querySelector('.tmf').value,duration:r.querySelector('.tmd').value,instruction:r.querySelector('.tmi').value})).filter(m=>m.medicine_name)};if(!t.name)return alert('ENTER TEMPLATE NAME.');x=x.filter(a=>a.id!==t.id);x.push(t);saveTemplateData(x);closeModal('templateEditor');loadTemplates();renderTemplateQuick()}
function loadTemplates(){let x=templateData();$('templateList').innerHTML=x.map(t=>`<div class="listrow"><div><b>${esc(t.name)}</b><div class="muted">${esc(t.diagnosis||'')} • ${(t.medicines||[]).length} MEDICINES</div></div><div class="actions"><button class="btn primary" onclick="route('consult');applyTemplate('${t.id}')">USE</button><button class="btn" onclick="openTemplateEditor(templateData().find(x=>x.id==='${t.id}'))">EDIT</button><button class="btn danger" onclick="deleteTemplate('${t.id}')">DELETE</button></div></div>`).join('')||'<p class="muted">NO TREATMENT TEMPLATES YET.</p>'}
function deleteTemplate(id){if(!confirm('DELETE THIS TREATMENT TEMPLATE?'))return;saveTemplateData(templateData().filter(t=>t.id!==id));loadTemplates();renderTemplateQuick()}
async function loadDashboard(){let s=await session();if(!s)return;let today=new Date(),iso=d=>d.toISOString().slice(0,10),to=iso(today),d7=new Date(today),d30=new Date(today);d7.setDate(d7.getDate()-6);d30.setDate(d30.getDate()-29);$('dashFrom').value=$('dashFrom').value||iso(d30);$('dashTo').value=$('dashTo').value||to;let p=await S.from('patients').select('id',{count:'exact',head:true}).eq('doctor_id',s.user.id);$('statPatients').textContent=p.count||0;let all=(await S.from('visits').select('visit_date').eq('doctor_id',s.user.id).gte('visit_date',iso(d30)).lte('visit_date',to).limit(5000)).data||[],counts={};all.forEach(v=>counts[v.visit_date]=(counts[v.visit_date]||0)+1);$('statToday').textContent=counts[to]||0;$('stat7').textContent=all.filter(v=>v.visit_date>=iso(d7)).length;$('stat30').textContent=all.length;let from=$('dashFrom').value,to2=$('dashTo').value,custom=(await S.from('visits').select('visit_date').eq('doctor_id',s.user.id).gte('visit_date',from).lte('visit_date',to2).limit(5000)).data||[],c={};custom.forEach(v=>c[v.visit_date]=(c[v.visit_date]||0)+1);let days=Object.keys(c).sort().reverse();$('visitCountTable').innerHTML='<table class="table"><tr><th>DATE</th><th>VISITS</th></tr>'+days.map(d=>`<tr><td>${esc(d)}</td><td>${c[d]}</td></tr>`).join('')+'</table>'+(days.length?'':'<p class="muted">NO VISITS IN THIS DATE RANGE.</p>')}
function closeOnEscape(e){if(e.key==='Escape')document.querySelectorAll('.modal.on').forEach(x=>x.classList.remove('on'))}
document.addEventListener('keydown',closeOnEscape);
document.addEventListener('click',e=>{const b=e.target.closest('.quick button');if(b&&b.dataset.target){e.preventDefault();insertText(b.dataset.target,b.dataset.text||b.textContent)}});
const _route=route;route=function(v){_route(v);setTimeout(()=>{fixConsultationUI();setupConsultTabOrder()},0)};
const _newConsult=newConsult;newConsult=function(){_newConsult();setTimeout(()=>{fixConsultationUI();setupConsultTabOrder()},0)};
async function showApp(){let s=await session();if(!s){$('login').classList.remove('hidden');$('app').classList.add('hidden');return}$('login').classList.add('hidden');$('app').classList.remove('hidden');$('visitDate').value=new Date().toISOString().slice(0,10);renderQuickButtons();renderTemplateQuick();setupConsultTabOrder();route(location.hash.replace('#','')||'home');fixConsultationUI()}
showApp();