/* Prime Hospital low-glare dark clinical theme + offline-first bootstrap */
(function(){
const css=`:root{--bg:#090d14;--panel:#101722;--panel2:#0c121c;--panel3:#151e2b;--text:#d8e2ee;--muted:#8b9aab;--line:#263447;--line2:#33445b;--cyan:#48d7e8;--focus:#71e4ff;--shadow:0 8px 28px rgba(0,0,0,.28)}
html,body{background:var(--bg)!important;color:var(--text)!important}body{font-family:Arial,sans-serif}body:before{content:"";position:fixed;inset:0;pointer-events:none;background:radial-gradient(circle at 15% 0%,rgba(72,215,232,.035),transparent 34%),radial-gradient(circle at 90% 20%,rgba(108,140,255,.035),transparent 32%);z-index:-1}
.card,.modalbox,.stat{background:var(--panel)!important;color:var(--text)!important;border-color:var(--line)!important;box-shadow:var(--shadow)!important}.brand{color:var(--cyan)!important}.brand h1{letter-spacing:.5px}.muted{color:var(--muted)!important}h2{color:#e4edf7}.section{border-top-color:var(--line)!important}.section h3{color:var(--cyan)!important}
.btn{background:var(--panel2)!important;color:var(--cyan)!important;border-color:#31506b!important;transition:.15s ease}.btn:hover{background:var(--panel3)!important;border-color:var(--cyan)!important;box-shadow:0 0 12px rgba(72,215,232,.12)}.btn.primary{background:#18264a!important;color:#9fb0ff!important;border-color:#586ed0!important}.btn.primary:hover{border-color:#7d92ff!important;box-shadow:0 0 14px rgba(108,140,255,.16)}.btn.danger{color:#ff9aa0!important;border-color:#71363d!important}.btn.danger:hover{border-color:#f07b83!important;box-shadow:0 0 12px rgba(240,123,131,.12)}
.field input,.field select,.field textarea,.search,.datebar input{background:#0a111a!important;color:var(--text)!important;border-color:var(--line2)!important;caret-color:var(--cyan)}.field input::placeholder,.field textarea::placeholder,.search::placeholder{color:#617084!important}.field input:focus,.field select:focus,.field textarea:focus,.search:focus,.datebar input:focus,.table input:focus{outline:2px solid rgba(113,228,255,.22)!important;border-color:var(--focus)!important;box-shadow:0 0 10px rgba(72,215,232,.08)!important}.field label{color:#9eafc2!important}
.quick button,.chips button{background:#0d1520!important;color:#9fb2c7!important;border-color:#293a4d!important}.quick button:hover,.chips button:hover{background:#172331!important;color:var(--cyan)!important;border-color:#4b7288!important}.table th,.table td{border-color:var(--line)!important;background:#0d141e;color:var(--text)}.table th{background:#151f2c!important;color:#9fdce5}.table input{background:transparent!important;color:var(--text)!important}.suggest{background:#0e1621!important;border-color:#36506a!important;box-shadow:var(--shadow)}.suggest div{border-bottom-color:var(--line)!important}.suggest div:hover{background:#172534!important}.listrow{background:#0d141e;border-color:var(--line)!important}.stat{background:#0d141e!important}.stat b{color:var(--cyan)!important}.modal{background:rgba(0,0,0,.72)!important}.tabs .btn{color:#b6c6d8!important}.tabs .btn:hover{color:var(--cyan)!important}
.nav .btn:nth-child(1){color:#8ec8ff!important;border-color:#294866!important}.nav .btn:nth-child(2){color:#9fb0ff!important;border-color:#586ed0!important}.nav .btn:nth-child(3){color:#69d6b1!important;border-color:#2d5d50!important}.nav .btn:nth-child(4){color:#e8c65a!important;border-color:#66562c!important}.nav .btn:nth-child(5){color:#e88bd7!important;border-color:#65405f!important}.nav .btn:nth-child(6){color:#e6a46a!important;border-color:#68472e!important}.nav .btn:nth-child(7){color:#ff929a!important;border-color:#71363d!important}.actions .btn{min-height:34px}input[type=date]::-webkit-calendar-picker-indicator{filter:invert(.75);opacity:.8}select option{background:#0d141e;color:var(--text)}#login .card{background:#0d141e!important}#login h1{color:var(--cyan)!important}#login h2{color:#dce8f5}#offlineStatus{font-size:11px;font-weight:700;padding:5px 9px;border:1px solid #31506b;border-radius:999px;background:#0c121c;color:#69d6b1;white-space:nowrap}#offlineStatus[data-state=offline]{color:#e8c65a;border-color:#66562c}#offlineStatus[data-state=online]{color:#69d6b1}@media(max-width:800px){.card{box-shadow:0 5px 18px rgba(0,0,0,.25)!important}}@media print{html,body{background:#fff!important;color:#111!important}.appscreen,.modal,#login{display:none!important}.printsheet{color:#111!important}}`;
const style=document.createElement('style');style.id='prime-low-glare-theme';style.textContent=css;document.head.appendChild(style);
function status(){let x=document.getElementById('offlineStatus');if(!x){x=document.createElement('div');x.id='offlineStatus';x.textContent=navigator.onLine?'ONLINE':'OFFLINE';const h=document.querySelector('#app header .head')||document.querySelector('#app header');if(h)h.appendChild(x)}if(window.PrimeData?.showOfflineStatus)window.PrimeData.showOfflineStatus()}
function loadOffline(){if(document.getElementById('prime-offline-loader'))return;const s=document.createElement('script');s.id='prime-offline-loader';s.src='/offline-db.js';s.onload=status;document.head.appendChild(s)}
loadOffline();
if('serviceWorker' in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});
window.addEventListener('online',status);window.addEventListener('offline',status);setTimeout(()=>{status();if(!navigator.onLine&&window.__primeOfflineOverrides&&window.showApp)window.showApp()},1200);
})();